### ISSUE TITLE
Disappearing Agent/Grid in Visualization

### ISSUE THREAD

**Issue by arata-tarata** [projectmesa/mesa#1056] opened 2021-09-12 07:52 UTC
Hello. I am working on a simple evacuation model on a basic multi-grid. The problem I am encountering occurs whenever I run the visualization. When I first open it in browser, the agents and the grid itself does not appear. I then press "reset". Sometimes things go back to normal, other times, only the agents appear or all continue to be hidden. Even with the times where the grid/agents do appear, they re-disappear within certain steps. What is going on here? What in my code is causing this issue?

I apologize in advance if this post lacks the necessary information. I did not know whether this is an easy-to-pin-down problem or not. Thanks.

**Comment by rht** [comment] 2021-09-12 12:29
You need to paste here the CLI log messages shown when you run the server. There should error messages buried down in the log.

**Comment by arata-tarata** [comment] 2021-09-14 04:02
Hm. I am not seeing any error messages when the grid/agents disappears. It doesn't matter if it is gone from the get-go or disappears after a certain steps, the error doesn't seem to show up.

**Comment by rht** [comment] 2021-09-14 13:13
Can you share the simplest code snippet that reproduces your problem?

**Comment by jackiekazil** [comment] 2021-11-27 03:40
Since there has been no reply this. I am going to close it. 
Please reopen when sharing your code or error.

**Closed by jackiekazil** 2021-11-27 03:40 UTC
