### ISSUE TITLE
reproducibility issue in the introductory tutorial due to MultiGrid.get_cell_list_contents()

### ISSUE THREAD

**Issue by alatti** [projectmesa/mesa#935] opened 2020-10-26 09:34 UTC
Hello,

The following line in the introductory tutorial (for me) produces an inconsistent ordering of cellmates when it is called each step:
`cellmates = self.model.grid.get_cell_list_contents([self.pos])`

I found this out when I set the model seed but was not able to achieve a reproducible result. The choice of items in the list is consistent (eg. choose the 2nd item) but the order of that list is not (eg. the list is sometimes ["a", "b"], sometimes ["b", "a"]). I would expect a consistent ordering of this list.

My solution, which achieved reproducibility, was to add the following line after the  `get_cell_list_contents` call but before the `random.choice` call:
`cellmates = [x for i, x in sorted([(x.unique_id, x) for x in cellmates])]`
This achieved a consistent ordering.

Kind regards,

Alex Latti

**Comment by Corvince** [comment] 2020-10-29 08:49
Thanks. The cell content was stored in a set, which has an unpredictable ordering in Python (and somewhat by definition). This is a duplicate of #782 and now fixed in master (but not yet released)

**Closed by Corvince** 2020-10-29 08:49 UTC
