### ISSUE TITLE
Cell space: Place agents in AgentSet randomly on (empty) cells

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2530] opened 2024-12-03 17:48 UTC
Often you create a bunch of Agents, and then you need to place them on the grid. Either you loop over them, or do some other unwieldy thing, none of it is elegant.

So it would be great if there was a simple function that would get all agents and place them on, optionally empty, cells. This could be implemented faster than placing them individually, since now only once has to be checked which cells are available / empty.

It's especially handy to be used together with `create_agents` (https://github.com/projectmesa/mesa/pull/2351), combined you can create and place all your agents with two lines of code.

```Python
some_agents = Ant.create_agents(n=100)
self.space.place_agents(some_agents, only_empty=True)
```

**Comment by quaquel** [comment] 2024-12-03 21:58
Yes either have a `place_agents` method, or have a way of getting a list of positions drawn either with it without replacement:

```python

cells = self.space.choices_empty_cells(100,) # with replacement, follows random.choices
cells = self.space.sample_empty_cells(100)  # no replacement, follows random.sample
```


```

**Comment by EwoutH** [comment] 2024-12-04 13:35
> once we agree on how to go about it: do it via sampling/choosing empty cells or do it via placing agents, or even have both?

Sorry, didn't recognize there also was a question in there. I would say its a two-stage function:
1. Select a random sample of cells, with or without replacement (keyword) and only empty or all (keyword)
2. Place the agents on these sampled cells.

**Comment by EwoutH** [comment] 2024-12-04 20:17
So we don't need anything new at all to do this. Damn. Powerful stuff.

I will update a few example models tomorrow.

**Comment by quaquel** [comment] 2024-12-04 20:20
`sample` and `choices` are currently not implemented on `CellCollection`, but `self.random.sample(self.space.empties, 100)` might already work.

**Comment by quaquel** [comment] 2024-12-06 10:50
I quickly checked, `self.random.sample(self.space.empties, k=100)` does not currently work. The issue is with the current implementation of `__getitem__`. A `CellCollection` is not a sequence, so `some_cellcollection[1]` does not work. Instead, currently `__getitem__` returns the agents for the cell. So it does `agents = some_cellcollection[my_cell]`. 

@Corvince, do you remember why `__getitem__` is implemented this way?

**Comment by Corvince** [comment] 2024-12-10 07:45
No I don't remember exactly, but yes, the `CellCollection` itself is more of like a dict than a sequence and you can't sample directly from a dict. But `CellCollection` also exposes a `cells` property. So I think `self.random.sample(self.space.empties.cells, k=100)` should work? It will give you a list of cells that you can use directly or just convert to another collection like `CellCollection(sampled_cells)`. Pretty flexible!

**Comment by EwoutH** [comment] 2024-12-10 08:23
Great insight! So now it's just:
```Python
some_empty_cells = self.random.sample(self.space.empties.cells, k=100)
some_agents = MyAgent.create_agents(n=100, cell=some_empty_cells)
```
Shows how powerful and flexible the cell space is.

**Comment by quaquel** [comment] 2024-12-12 07:22
I added this to some of the examples so it is clear to others as well how to do this. I am closing this issue.

**Closed by quaquel** 2024-12-12 07:22 UTC
Labels: enhancement
