### ISSUE TITLE
WolfSheep won't show wolves or sheep

### ISSUE THREAD

**Issue by ntguardian** [projectmesa/mesa#379] opened 2017-05-28 03:36 UTC
I wanted to run the WolfSheep example to see if the wolves and sheep would be drawn in the visualization (that is, the .png files in resources). There were no wolves or sheep, just grass.

**Comment by Corvince** [comment] 2017-05-30 08:18
Could you try clearing the cache? Usually all you need to do for that is to reload the browser tab with Ctrl-F5 or Shift-F5

**Comment by ntguardian** [comment] 2017-06-02 14:17
I did that. No sign of wolves or sheep.

**Comment by rht** [comment] 2017-07-07 08:35
@ntguardian do you have error log in the browser console you are running? In which directory did you run the WolfSheep example from (mesa/examples or mesa/examples/wolf_sheep)? I can reproduce your problem by running it from mesa/examples. If this is indeed the cause of the problem, the issue can be closed. And have fun with the simulations, or if you have any further tweaks!

**Comment by jackiekazil** [comment] 2017-11-12 00:08
@rht thank you for your review. 

I am closing this ticket for now. 
Please reopen if still relevant.

**Closed by jackiekazil** 2017-11-12 00:08 UTC
