### ISSUE TITLE
Introductory Tutorial Is Wrong I Think (But I'm New To Mesa)

### ISSUE THREAD

**Issue by ericssimpson** [projectmesa/mesa#1299] opened 2022-04-30 19:07 UTC
https://mesa.readthedocs.io/en/stable/tutorials/intro_tutorial.html
In the intro tutorial for batch runs it says to do the following:

```
from mesa.batchrunner import batch_run
params = {"width": 10, "height": 10, "N": range(10, 500, 10)}

results = batch_run(
    MoneyModel,
    parameters=params,
    iterations=5,
    max_steps=100,
    number_processes=None,
    data_collection_period=1,
    display_progress=True,
)
```

Which doesn't work.

Instead, I followed the code from here for setting up the batch run:
https://github.com/projectmesa/mesa-examples/blob/master/examples/Tutorial-Boltzmann_Wealth_Model/.ipynb_checkpoints/Introduction%20to%20Mesa%20Tutorial%20Code-checkpoint.ipynb

Code actually runs.

Reporting my help/issue in haste, currently working on final projects in school, I'll expand on it later if you need more detail. Seems to be just an issue with the tutorial.

**Comment by rht** [comment] 2022-04-30 22:23
Thank you for the report.
The `batch_run` one is newer. https://github.com/projectmesa/mesa-examples/blob/master/examples/Tutorial-Boltzmann_Wealth_Model/.ipynb_checkpoints/Introduction%20to%20Mesa%20Tutorial%20Code-checkpoint.ipynb uses master branch, which has been replaced with main.
But I can't conclude anything unless you posted your error message.

**Comment by tpike3** [comment] 2022-05-01 11:14
@ericssimpson Thanks! I noticed the url with an issue was on the stable version, I have inactivated stable. The [latest read the docs](https://mesa.readthedocs.io/en/latest/)  has the same information at the jupyter tutorial

**Comment by rht** [comment] 2022-05-01 11:19
The version that was reported to be not working the `batch_run` one, so I think the issue is still unresolved because we don't know what the error message was.

**Comment by tpike3** [comment] 2022-05-01 11:20
@rht fair point, @ericssimpson please let us know the error message.

**Comment by ericssimpson** [comment] 2022-05-01 18:01
No error message, just no advancement of the iteration and freezing of the notebook when I try to interrupt and stop. I'm running it in Jupiter Notebook on Windows 10. I tried the multiprocessor stuff as well. Didn't have to do the multiprocessor stuff when trying out the example within the alternative batch run code I posted above.

**Comment by tpike3** [comment] 2022-05-15 11:44
@ericssimpson multi-processing is always nuanced so if you could post a link to your code and let us know you OS that would be helpful.

**Comment by rht** [comment] 2022-05-16 08:48
I'm closing this issue because OP hasn't provided enough detail to reproduce the problem.
(We should clean up GH issues that can't be reproduced)

**Closed by rht** 2022-05-16 08:48 UTC
