### ISSUE TITLE
Allow multiple agents in the same location

### ISSUE THREAD

**Issue by Pieter-Cawood** [projectmesa/mesa#1305] opened 2022-05-08 23:03 UTC
**Exception when more than one agent is at the same location**
[These lines ](https://github.com/projectmesa/mesa/blob/006359b2a7e9a3b550b790c1b16c5a089521bb27/mesa/time.py#L63-L66)
cause an exception when more than one agent is at the same location.

**The solution I'd like**
Some agents in my scenario need to be in the same location at the same time. This should be configurable whether it is allowed.

**Comment by rht** [comment] 2022-05-09 00:19
Those lines are from the scheduler, not the space module. And the problem is that you're using a duplicate unique identifier for the agent. If you want multiple agents in the same grid location, you use MultiGrid.

**Comment by tpike3** [comment] 2022-05-10 19:35
@Pieter-Cawood  I am going to close this issue as `mesa.space.MultiGrid` allows multiple agents at one location. Please refer to the [adding Space portion of the Mesa tutorial](https://mesa.readthedocs.io/en/latest/tutorials/intro_tutorial.html#adding-space) to see how.

Please let us know if you have any other questions or concerns.

**Closed by tpike3** 2022-05-10 19:35 UTC
