### ISSUE TITLE
Histogram not working in adv tutorial 

### ISSUE THREAD

**Issue by CrockettJF** [projectmesa/mesa#609] opened 2018-12-12 22:35 UTC
First off -- Thanks for all the work on mesa, this is an awesome package that has been very useful.

Second - I have very little experience with js so that may be my issue, but after a good while checking into it, I think that if it is my issue then the tutorial needs some updating somewhere so that it can be better followed.

**Describe the bug**

According to the last section of the advanced tutorial, following the steps should produce a histogram.
**Expected behavior**

I expect there to be three separate different visualizations. The canvas grid, the chart, and then the histogram. 

**To Reproduce**

The tutorial code that I have (mostly copied) from both sections of the documentation can be found [here](https://github.com/CrockettJF/mesa-testing).

**Comment by dmasad** [comment] 2018-12-13 03:42
Good catch! It looks like there's been a change to the charts.js API that hasn't been updated in the tutorial.

We need to update the tutorial itself, but a sketch of the solution is:

In `HistogramModule.js`, line 38 and 49 are updated to look like:

```js
var chart = new Chart(context, 
        {'type': 'bar', 'data': data, 'options': options});
```

Line 43 is updated to:

```js
chart.data.datasets[0].data[i] = data[i];
```

Finally, to have it add the histogram to the page directly, line 10 should be:
```js
$("#elements").append(canvas);
```

The one remaining issue is that this seems to draw the histogram overlapping with the line chart. I'll try to figure that out -- but if anyone knows the HTML/CSS(?) issue going on here, feel free to jump in!

**Comment by CrockettJF** [comment] 2018-12-13 15:36
Awesome, thanks. 

There were a couple of other little tweaks that I had to make with those same ideas, but I got it to work and I never ran into the issue of overlapping graphs. Below is the entire `HistogramModule.js` for reference.

```js

// HistogramModule.js
var HistogramModule = function(bins, canvas_width, canvas_height) {
    // Create the elements

    // Create the tag:
    var canvas_tag = "<canvas width='" + canvas_width + "' height='" + canvas_height + "' ";
    canvas_tag += "style='border:1px dotted'></canvas>";
    // Append it to body:
    var canvas = $(canvas_tag)[0];
    $("#elements").append(canvas);
    // Create the context and the drawing controller:
    var context = canvas.getContext("2d");

    // Prep the chart properties and series:
    var datasets = [{
        label: "Data",
        fillColor: "rgba(151,187,205,0.5)",
        strokeColor: "rgba(151,187,205,0.8)",
        highlightFill: "rgba(151,187,205,0.75)",
        highlightStroke: "rgba(151,187,205,1)",
        data: []
    }];

    // Add a zero value for each bin
    for (var i in bins)
        datasets[0].data.push(0);

    var data = {
        labels: bins,
        datasets: datasets
    };

    var options = {
        scaleBeginsAtZero: true
    };

    // Create the chart object
    var chart = new Chart(context,{'type': 'bar', 'data': data, 'options': options});

    // Now what?
    this.render = function(data) {
        for (var i in data)
            chart.data.datasets[0].data[i] = data[i];
        chart.update();
    };

    this.reset = function() {
        chart.destroy();
        chart = new Chart(context,{'type': 'bar', 'data': data, 'options': options});
    };
};
```

**Comment by CrockettJF** [comment] 2018-12-13 15:36
reopened just in case this is a place holder for the tutorial fix.

**Comment by dmasad** [comment] 2018-12-14 03:18
Thanks, that looks great! If you want, you're welcome to open a pull request to update the tutorial with the correct code. Otherwise we'll aim to do that ASAP.

**Comment by dmasad** [comment] 2018-12-14 03:53
Also, just FYI -- the code you wrote based on the tutorial isn't fully in line with the most recent Mesa API. (Since the `latest` branch apparently isn't up to date). The main change is that models now have their own random number generator with a seed stored for reproducible, so instead of importing `random` and using `random.random()`, you can call `self.random.random()` from within a model or agent object.

**Comment by CrockettJF** [comment] 2018-12-14 03:56
I should be able to get to it in the next couple of days so I can fix it.

I hadn’t realized that! I’ll make sure to have that updated in my pull request. Thanks!

On Dec 13, 2018, at 9:53 PM, David Masad <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, just FYI -- the code you wrote based on the tutorial isn't fully in line with the most recent Mesa API. (Since the latest branch apparently isn't up to date). The main change is that models now have their own random number generator with a seed stored for reproducible, so instead of importing random and using random.random(), you can call self.random.random() from within a model or agent object.

**Comment by jackiekazil** [comment] 2018-12-22 12:30
Playing a little catch up... 
@dmasad RE: your comment - "Since the latest branch apparently isn't up to date" -- just so I understand this correctly are you saying that @CrockettJF's branch isn't up to date? 

@CrockettJF - It looks like you have never made a pull request before. Let us know if you have any questions or need help.

**Comment by jackiekazil** [comment] 2019-05-06 21:04
I am going to close this ticket in lieu of #610. 
@CrockettJF, please comment on #610 if you are going to submit the PR. And also let us know if you need any help figuring it.

**Closed by jackiekazil** 2019-05-06 21:04 UTC

**Comment by Trainwithvinny** [comment] 2019-05-09 17:37
@kennethells @dmasad Hey, is there now a workaround so that we can see the histo and line chart seperately?

**Comment by jackiekazil** [comment] 2019-05-10 02:12
@Trainwithvinny that sounds like an issue that is separate from this issue. Can you fill a new bug with more details?

**Comment by MartiinGE** [comment] 2019-12-20 15:12
Thank you very much for the fix.
The dataset properties are not correct. If you want to change color it would be backgroundColor etc.
https://www.chartjs.org/docs/latest/charts/bar.html
