### ISSUE TITLE
Error to run the model

### ISSUE THREAD

**Issue by LuizFilippe1995** [projectmesa/mesa#874] opened 2020-07-29 21:06 UTC
**Describe the bug**
Sorry, I'm new to GitHub and Python. I'd like to apologize because my question is too basic. When I run the model in the section "Running your first model", the following error is returned: " 'MoneyAgent' object has no attribute 'random' ". I have downloaded all the requirements and my Python is up to date. Then, I really do not know what is happening. Could you please help me? Thanks very much indeed!

![Sem título](https://user-images.githubusercontent.com/53869523/88853297-e3460200-d1c5-11ea-9f4c-a0c5dbca337b.png)

**Comment by tpike3** [comment] 2020-07-30 13:18
Can you show your imports?

**Comment by LuizFilippe1995** [comment] 2020-07-30 14:04
Yes! These are my imports for the model:

`from mesa import Agent, Model`
`from mesa.time import RandomActivation`
`import random`

When it comes to Mesa, I only used the code to install it:

`$ pip install mesa`

**Comment by LuizFilippe1995** [comment] 2020-07-30 14:05
> Can you show your imports?

Yes! These are my imports for the model:

`from mesa import Agent, Model`
`from mesa.time import RandomActivation`
`import random`

When it comes to Mesa, I only used the code to install it:

`$ pip install mesa`

**Comment by tpike3** [comment] 2020-07-30 14:46
OK, I think I recreated your error. Make sure you are inheriting the Mesa Agent Class. The initiation of the MoneyAgent class should read like below. The (Agent) next to MoneyAgent pass through Agent classes attributed which includes random. 

`class MoneyAgent(Agent):`
    `""" An agent with fixed initial wealth."""`
    `def __init__(self, unique_id, model):`
        `super().__init__(unique_id, model)`
        `self.wealth = 1    `

**Comment by tpike3** [comment] 2020-07-30 17:43
Hmmmm...using your code I am not getting the error. What version of python are you using?

**Comment by LuizFilippe1995** [comment] 2020-07-30 17:55
> Hmmmm...using your code I am not getting the error. What version of python are you using? Are you using an IDE like Syder or PyCharm?

RealIy? That is intriguing... I am using Python 3.7.7 and my IDE is Jupyter.

**Comment by tpike3** [comment] 2020-07-30 18:12
Could you shoot me your list of dependencies. You should be able to "pip list" in your terminal, it should look something like 
 
ipython            7.13.0
mesa                0.8.4 ...

**Comment by LuizFilippe1995** [comment] 2020-07-30 19:04
> Could you shoot me your list of dependencies. You should be able to "pip list" in your terminal, it should look something like
> 
> ipython 7.13.0
> mesa 0.8.4 ...

Yeah. Here you have:

![1](https://user-images.githubusercontent.com/53869523/88963208-e8668800-d27d-11ea-9441-b45b797e2e3a.png)
![2](https://user-images.githubusercontent.com/53869523/88963211-e997b500-d27d-11ea-8d3f-06d65c802067.png)
![3](https://user-images.githubusercontent.com/53869523/88963213-e997b500-d27d-11ea-8bae-ac6cf0bffab9.png)
![4](https://user-images.githubusercontent.com/53869523/88963216-ea304b80-d27d-11ea-9b0d-a0414b0c6eca.png)
![5](https://user-images.githubusercontent.com/53869523/88963218-ea304b80-d27d-11ea-8638-14c6e84a6cce.png)
![6](https://user-images.githubusercontent.com/53869523/88963220-eac8e200-d27d-11ea-876f-c732a6e7c72b.png)
![7](https://user-images.githubusercontent.com/53869523/88963295-0502c000-d27e-11ea-83de-c282d79a9cd2.png)

**Comment by tpike3** [comment] 2020-07-31 18:38
Luiz: I think the issue is you are are using Mesa 0.8.3 instead of 0.8.7. I am not sure why if you did pip install it did 0.8.3. but you can upgrade to the latest version by doing
`pip install mesa --upgrade` 
or do

`pip uninstall mesa`
`pip install mesa==0.8.7`

**Comment by LuizFilippe1995** [comment] 2020-07-31 19:43
> Luiz: I think the issue is you are are using Mesa 0.8.3 instead of 0.8.7. I am not sure why if you did pip install it did 0.8.3. but you can upgrade to the latest version by doing
> `pip install mesa --upgrade`
> or do
> 
> `pip uninstall mesa`
> `pip install mesa==0.8.7`

That is it! I updated mesa and now it is working. Thank you a lot, Pike!

**Closed** 2020-07-31 19:44 UTC
