### ISSUE TITLE
Adding a Text "Output" Box

### ISSUE THREAD

**Issue by narc98** [projectmesa/mesa#404] opened 2017-08-18 03:42 UTC
Your project is a great launching pad for my ABM work.  I'm curious if there's a mechanism to add something like a TextData element to the overall server window (for instance, the Wolf/Sheep ModularServer).  I have added a few different charts to monitor variables in my model but would like to add another module that simply displays the contents of a dictionary (concept in the attached picture).  This behavior either doesn't exist or I can't solve how to add that element to the server (which I presume is probably the case).  Thanks for any help anyone can offer.  

Nate

![textbox](https://user-images.githubusercontent.com/15098762/29443321-26e7e50e-838c-11e7-8361-305322fda7d2.png)

**Comment by narc98** [comment] 2017-08-20 17:27
For clarification purposes, I tried creating a simple "TextData" element and adding it to the call to the ModularServer constructor (throws a "AttributeError: 'TextData' object has no attribute 'package_includes').   I also tried the sample code concept from the tutorials/modular-visualization.rst file (lines 117-165), but that throws the same error.  If I just add the missing variables to the "AttributeElement" class, then the server will open, but a "TypeError: render() takes 1 positional argument but 2 were given" (line 322 from ModularVisualization.py).  I can't trace why multiple arguments are being passed there (I have not modified any of the base Mesa code).

**Comment by dmasad** [comment] 2017-08-21 01:00
That's definitely a good idea! The documentation on readthedocs was slightly out of date; that's fixed now. Can you post your code on here or in a gist or something? That'll make it easier to see what the issue is.

**Comment by narc98** [comment] 2017-08-22 19:51
https://gist.github.com/narc98/3bd3b0617958047d19ef5a4227818c1e

Sure.  I'm working on a model where drones (agents) depart a location and search a given area and report back to a Command/Control agent if they find any objects.  My "Operator" class just has some basic movement behaviors (moveToPos(pos), stayCloseToPos(distance), etc..).  Each step, I'd like to show what's in the C2.investigate and C2.tracking dictionaries in the main window.  

Thanks very much for taking a look,
Nate

**Comment by jackiekazil** [comment] 2019-05-06 20:21
@dmasad 
1. I am going thru old tickets. Is there something here to update on the docs or no?
2. Should we create a new ticket for this or retitle this one for the feature add?

**Comment by quaquel** [comment] 2024-10-30 18:01
this is easy to do with solara and covered in some of the examples on read the docs.

**Comment by EwoutH** [comment] 2024-10-30 18:50
For example:

https://mesa.readthedocs.io/latest/examples/schelling.html

**Closed by EwoutH** 2024-10-30 18:51 UTC
Labels: 0 - Triage
