### ISSUE TITLE
DataCollector.collect() overwrites agent_vars each step

### ISSUE THREAD

**Issue by elcombato** [projectmesa/mesa#312] opened 2016-09-02 09:33 UTC
Hi,

I'm struggling with a strange problem. This snippet is the simplest code to reproduce the behavior:

``` python
from random import random
from mesa import Model, Agent
from mesa.datacollection import DataCollector
from mesa.time import BaseScheduler


class Agentus(Agent):
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.unique_id = unique_id
        self.data = [0.0, 0.0]

    def step(self):

        # NOT WORKING
        self.data[0] = random()
        self.data[1] = random()

        # WORKING
        # self.data = [random(), random()]


class Modelus(Model):
    def __init__(self):
        super().__init__()
        self.schedule = BaseScheduler(self)

        for i in range(10):
            agent = Agentus(i, self)
            self.schedule.add(agent)

        self.datacollector = DataCollector(
            agent_reporters={"total": lambda a: a.data}
        )

    def step(self):
        self.datacollector.collect(self)
        self.schedule.step()

```

If I run this model for some steps and call `model.datacollector.get_agent_vars_dataframe()`, the resulting data is the same for each step. But if the `data` in `Agent.step()` is assigned with `self.data = [random(), random()]` the resulting data is correct and differs in each step as expected.

Debugging in [`DataCollector.collect()`](https://github.com/projectmesa/mesa/blob/master/mesa/datacollection.py#L133) tells me, that `agent_vars` has the data values of the current step assigned to all steps in the list, even before `agent_records` is filled with the data from the current step.

edit: I'm working with Mesa 0.7.7 and Python 3.5.2

**Comment by elcombato** [comment] 2016-09-02 11:23
Printing `agent_vars` in `Agent.step()` reveals, that it is altered simultanesouly to `Agent.data`. How is that possible?!
```python
class Agentus(Agent):
...
    def step(self):

        # NOT WORKING
        print("____Agent "+str(self.unique_id))
        print(self.model.datacollector.agent_vars)
        self.data[0] = random()
        print(self.model.datacollector.agent_vars)
        self.data[1] = random()
        print(self.model.datacollector.agent_vars)
```
Console Output:
```
____Agent 0
{'total': [[(0, [0.0, 0.0]), (1, [0.0, 0.0]), (2, [0.0, 0.0]), (3, [0.0, 0.0]), (4, [0.0, 0.0])]]}
{'total': [[(0, [0.9085024773916184, 0.0]), (1, [0.0, 0.0]), (2, [0.0, 0.0]), (3, [0.0, 0.0]), (4, [0.0, 0.0])]]}
{'total': [[(0, [0.9085024773916184, 0.8905327510148061]), (1, [0.0, 0.0]), (2, [0.0, 0.0]), (3, [0.0, 0.0]), (4, [0.0, 0.0])]]}
____Agent 1
{'total': [[(0, [0.9085024773916184, 0.8905327510148061]), (1, [0.0, 0.0]), (2, [0.0, 0.0]), (3, [0.0, 0.0]), (4, [0.0, 0.0])]]}
{'total': [[(0, [0.9085024773916184, 0.8905327510148061]), (1, [0.7716049548907735, 0.0]), (2, [0.0, 0.0]), (3, [0.0, 0.0]), (4, [0.0, 0.0])]]}
{'total': [[(0, [0.9085024773916184, 0.8905327510148061]), (1, [0.7716049548907735, 0.839280788005374]), (2, [0.0, 0.0]), (3, [0.0, 0.0]), (4, [0.0, 0.0])]]}
...
```

**Comment by elcombato** [comment] 2016-09-02 11:52
I found a workaround:
```python
self.datacollector = DataCollector(
    agent_reporters={"total": lambda a: a.data*1}
)
```
by adding `*1`, this strange link between `Agent.data` and `DataCollector.agent_vars` is somehow removed.

**Comment by njvrzm** [comment] 2016-09-02 20:24
The more usual way to implement the workaround you give would be to use
```python
agent_reports = {"total": lambda a:list(a.data)}
```
but they're functionally the same.

The problem is that the lambda in the original code is handing a reference to the agent's data list off to the `DataCollector`. The very same list is collected at every step - not a copy of the list, but the same object. The agent's `step()` method modifies that object, and those modifications are visible everywhere the object exists - including every collected record for the agent. You can see the essence of the problem with this code:
```python
In [1]: a = [1, 2, 3]
In [2]: b = []
In [3]: b.append(a)
In [4]: b
Out[4]: [[1, 2, 3]]
In [5]: a.append(5)
In [6]: b
Out[6]: [[1, 2, 3, 5]]

```
The "WORKING" code replaces Agent.data at every step, and so each record collected by the DataCollector contains a different list object. Making a copy with `list(a.data)` accomplishes the same thing while allowing you to modify the agent's `data` attribute.

It's probably worth considering changing the data collector to do a `copy.deepcopy` on the data it's given to avoid the need for the workaround. @jackiekazil?

**Comment by jackiekazil** [comment] 2018-11-02 13:04
@njvrzm this is still relevant yes? (I believe it is.)  Will you create a ticket for copy.deepcopy suggestion to separate it out from this ticket? (If not, I will.)

**Comment by tpike3** [comment] 2020-08-08 16:32
Closing based on time past and Mesa updates

**Closed by tpike3** 2020-08-08 16:32 UTC
Labels: 0 - Triage
