### ISSUE TITLE
Example model running issues

### ISSUE THREAD

**Issue by devforfu** [projectmesa/mesa#542] opened 2018-05-23 11:07 UTC
Probably not a big deal, but I have a few issues while trying to invoke [Schelling model](https://github.com/projectmesa/mesa/tree/master/examples/Schelling) on my machine. (Though I guess same issues would have arisen with other models, except the first one).

1) The `mesa run` command fails with "command not found" error. Do I need to adjust my path variable?
```
$ mesa run
zsh: command not found: mesa
```
2) When I use `python run.py`, it tries to open a browser. But I am running `mesa` on remote "headless" Ubuntu server and open browser on my local machine instead. I can access the notebook, but ssh connection invokes X-term window with Firefox Browser. Is it possible to disable automatic browser opening?

3) **[Minor issue]** Dots are not colored
![model](https://user-images.githubusercontent.com/6022009/40420324-8a851014-5ea1-11e8-8be8-9ae14ebe4442.png)

Do you think that something is wrong with my installation or environment configuration? Or these points are expected behaviour?

Here is a sequence of commands I use to install `mesa` and to run a model:
```
$ source activate venv
(venv) $ pip install mesa
(venv) $ git clone https://github.com/projectmesa/mesa.git mesa_repo
(venv) $ cd mesa_repo/examples/Schelling
(venv) $ mesa run   # fails
zsh: command not found: mesa
(venv) $ python run.py  # opens Firefox on remote host
```

**Comment by jackiekazil** [comment] 2018-05-24 03:40
**RE: 1**
can you let me know what is your path? 
Just incase you don't know... 
```
import sys, pprint
pprint.pprint(sys.path)
```

**RE: 2** 
I am trying to follow your description and I am not sure I understand why you included this -- "I can access the notebook, but ssh connection invokes X-term window with Firefox Browser." What is the relevance of that to your request? 

**RE: 3**
With the latest that is in master, `mesa run` works for me and I see the following... 

<img width="1070" alt="screen shot 2018-05-23 at 11 32 58 pm" src="https://user-images.githubusercontent.com/166734/40463217-f9c57cbc-5ee1-11e8-85bc-8b4966b183b5.png">

**Comment by digitaldust** [comment] 2018-05-28 13:10
same issue here, all dots are black. I am on Mac OSX 10.13.4, the issue is both on Safari and Chrome, but no errors in both JS Consoles.

As suggested in the google group, I tried to change in the schelling_draw() function the portrayal["Color"] lines from lists to just the single red/blue color values, and it worked fine. 

So I guess the problem is to handle the list of colors?

**Comment by djmitche** [comment] 2018-06-18 13:20
@justinhastings have you "installed" mesa into the virtualenv?  Something like `pip install mesa` or (as it looks like you're working in the git repository) `pip install -e .` in the "Mesa" directory.

**Comment by dmasad** [comment] 2018-07-21 20:54
Is this resolved by the solution in #553?

**Comment by devforfu** [comment] 2018-07-24 15:38
@jackiekazil @dmasad Yes, the most recent `master` solves the problem for me when is installed in the editing mode, as advised:
```
mesa_repo$ pip install -e .
```
@jackiekazil About the second bullet, I mean that I am running mesa on a remote host and when I invoke `mesa runserver`, it tries to open the browser _on that remote machine_, like:
![screenshot](https://user-images.githubusercontent.com/6022009/43149677-7d8c4f7e-8f81-11e8-8543-878cf76ae452.png)

**Comment by ChanakyaBandara** [comment] 2020-05-05 04:18
When i try to 

> mesa runserver

its start the Interface, But gives an NotImplementedError.
<img width="846" alt="Capture" src="https://user-images.githubusercontent.com/44600363/81034675-8d5b0a00-8eb5-11ea-997e-068c7ef793e1.PNG">

**Comment by Corvince** [comment] 2020-05-05 17:55
> When i try to
> 
> > mesa runserver
> 
> its start the Interface, But gives an NotImplementedError.

Seems to be an issue with Python 3.8 on Windows and Tornado, see [this discussion](https://github.com/tornadoweb/tornado/issues/2608)

A workaround seems to be to put this into the beginning of your `run.py` file (untested):
```python
import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by jackiekazil** [comment] 2020-05-10 14:54
@ChanakyaBandara please let us know if that worked for you just in case others encounter that issue.

Closing this ticket, because it seems to be a hodge podge that is dragging on with no clear action needed at this time. Added #834 as a feature.

**Closed by jackiekazil** 2020-05-10 14:54 UTC
Labels: 0 - Triage

**Comment by ChanakyaBandara** [comment] 2020-05-10 15:00
> @ChanakyaBandara please let us know if that worked for you just in case others encounter that issue.
> 
> Closing this ticket, because it seems to be a hodge podge that is dragging on with no clear action needed at this time. Added #834 as a feature. 

Yaa it works , thankz a lot

**Comment by jackiekazil** [comment] 2020-05-10 15:12
Awesome! Thank you so much! That comment can really help others who may encounter the issue in the future!
