### ISSUE TITLE
RandomActivation scheduler not working after upgrade 2.1 -> 2.2.3

### ISSUE THREAD

**Issue by profConradi** [projectmesa/mesa#2006] opened 2024-01-24 20:29 UTC
I upgraded 2.1 to 2.2.3 and in this simple test model RandomActivation scheduler does not work anymore: agent activation is done sequentially.
Furthermore if I not call super().__init__() in the model class, the first agent is not added to the scheduler. Is this a bug or a mistake on my part?

```python
    class CognitiveAgent(mesa.Agent):
        """Agents make decisions using automatic (e.g., reflexive) versus controlled (e.g., deliberative) cognition,
        interact with each other, and influence the environment (i.e., game payoffs)."""
    
        def __init__(self, unique_id, model):
            # Pass the parameters to the parent class.
            super().__init__(unique_id, model)
    
            # Each agent is defined by a single parameter x that represents its probability of controlled processing
            self.xdx = np.random.uniform(0., 1.)
    
        def step(self):
            # The agent's step will go here.
            # For demonstration purposes we will print the agent's unique_id
            other_agent = self.random.choice(self.model.schedule.agents)
            print(f"I'm {self.unique_id} and I choose {other_agent.unique_id}")
            
    class CognitiveModel(mesa.Model):
        """A model with some number of agents."""
    
        def __init__(self, N):
            super().__init__()
            self.num_agents = N
            self.schedule = mesa.time.RandomActivation(self)
            # Create agents
            for i in range(self.num_agents):
                a = CognitiveAgent(i, self)
                # Add the agent to the scheduler
                print(a,i)
                self.schedule.add(a)
    
        def step(self):
            """Advance the model by one step."""
            # The model's step will go here for now this will call the step method of each agent and print the agent's unique_id
            self.schedule.step() 
```

**Comment by EwoutH** [comment] 2024-01-26 11:15
I've narrowed it down to the fact that the AgentSet's `shuffle(inplace=True)` doesn't shuffle the agents. Could be because the shuffle isn't working, or the in place updating isn't.

https://github.com/projectmesa/mesa/blob/99b35fcacadacae1d2860c86ac370f262a70da93/mesa/time.py#L144-L147

![Screenshot_366](https://github.com/projectmesa/mesa/assets/15776622/85c66aff-fe7d-4f63-8fe2-f026d46f0943)

**Comment by EwoutH** [comment] 2024-01-26 11:18
It's the inplace updating that isn't working. Without it, it works correctly:

![Screenshot_367](https://github.com/projectmesa/mesa/assets/15776622/1d976ddb-d13e-4a1a-8e1a-af701689bd9d)

@quaquel you wrote this code and know more about the AgentSet implementation. Could assist in fixing the inplace updating?

**Comment by profConradi** [comment] 2024-01-26 11:54
Thank for your works, Mesa is an amazing framework!

**Comment by quaquel** [comment] 2024-01-26 12:01
I can try this afternoon. I don't see an obvious mistake in the code.

AgentSet.shuffle

```python
        shuffled_agents = list(self)
        self.random.shuffle(shuffled_agents)

        return (
            AgentSet(shuffled_agents, self.model)
            if not inplace
            else self._update(shuffled_agents)
        )
```

random.shuffle is inplace. List(self) returns a list of hard refs to the agents.

AgentSet._update

```python
    def _update(self, agents: Iterable[Agent]):
        """Update the AgentSet with a new set of agents.
        This is a private method primarily used internally by other methods like select, shuffle, and sort.
        """

        self._agents = weakref.WeakKeyDictionary({agent: None for agent in agents})
        return self
```


We create a new WeakKeyDictionary so it should shuffle.

Accidentally, This is the code I was playing with for #1993. So my to do;

- [ ] add a unittest that reproduces the error
- [ ] figure out why the error exists, because based on the code I don't
- [ ] test my fix from #1993

**Comment by EwoutH** [comment] 2024-01-26 12:27
Thanks. I had already written an additional unittest for RandomActivation itself, we can test updates also against that (#2007).

**Comment by quaquel** [comment] 2024-01-26 12:50
Found it. The problem is in the scheduler not in AgentSet.

do_each should be

```python
    def do_each(self, method, shuffle=False):
        if shuffle:
            self._agents.shuffle(inplace=True)
        self._agents.do(method)

```

**Comment by quaquel** [comment] 2024-01-26 13:04
I committed the fix to #2007.

**Closed** 2024-01-26 17:01 UTC
Labels: bug

**Comment by EwoutH** [comment] 2024-01-26 21:52
@profConradi we just released Mesa 2.2.4 which should fix this issue. Could you confirm this is the case?

**Comment by profConradi** [comment] 2024-01-26 21:58
Yes, the RandomActivation Scheduler of 2.2.4 works correctly! Thanks!

**Comment by EwoutH** [comment] 2024-01-26 22:34
Great to hear, thanks a lot for reporting this issue!

For such a serious bug to slip thought the the review, test and release process is really unfortunate. I wrote some thoughts on it here: https://github.com/projectmesa/mesa/discussions/1909#discussioncomment-8262110
